version: 2

models:
  - name: stg_orders
    description: "Orders table with order-level attributes"
    columns:
      - name: order_id
        description: "Primary key of order"
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: order_dow
      - name: order_hour_of_day
      - name: days_since_prior_order

  - name: stg_products
    description: "Products with aisle and department ids"
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: aisle_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_aisles')
              field: aisle_id
      - name: department_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_departments')
              field: department_id

  - name: stg_aisles
    description: "Aisles dimension"
    columns:
      - name: aisle_id
        tests: [not_null, unique]

  - name: stg_departments
    description: "Departments dimension"
    columns:
      - name: department_id
        tests: [not_null, unique]

  - name: stg_order_products_prior
    description: "Products inside prior orders"
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

  - name: stg_order_products_train
    description: "Products inside train orders"
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
