version: 2

models:
  - name: dim_products
    description: "Dimension products (enriched with aisle & department)"
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: dim_customers
    description: "Customer dimension (unique users)"
    columns:
      - name: user_id
        tests: [unique, not_null]

  - name: fct_orders
    description: "Fact table: orders x order_products_prior"
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
