name: 'instacart_c360'
version: '1.0'
config-version: 2
profile: 'instacart_c360'

model-paths: ['models']
target-path: 'target'
clean-targets: ['target','dbt_packages']

models:
  instacart_c360:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table
